spl_add_include(${PROJECT_SOURCE_DIR}/components/b/src)
spl_add_include(${PROJECT_SOURCE_DIR}/components/headlights/src)
spl_add_include(${PROJECT_SOURCE_DIR}/components/led_hw/src)
spl_add_include(${PROJECT_SOURCE_DIR}/components/voltage_adc/src)
spl_add_include(${PROJECT_SOURCE_DIR}/components/network/src)

spl_add_component(components/calc)
spl_add_component(components/a)
spl_add_component(components/moving_average)
spl_add_component(components/diagnostic)
spl_add_component(components/led)
spl_add_component(components/voltage_converter)
spl_add_component(components/voltage_monitor)
spl_add_component(components/power_manager)
